# Generated by Django 4.0.4 on 2022-04-20 06:30

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinicapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('update_date', models.DateField(auto_now_add=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('quantity', models.IntegerField()),
                ('price', models.CharField(max_length=255, null=True)),
                ('description', ckeditor.fields.RichTextField(max_length=255, null=True)),
                ('image', models.ImageField(upload_to='medicine/%Y/%m')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='receipt_medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('update_date', models.DateField(auto_now_add=True)),
                ('symptom', ckeditor.fields.RichTextField(max_length=255)),
                ('diagnostic', ckeditor.fields.RichTextField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='receipt_medicine_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('update_date', models.DateField(auto_now_add=True)),
                ('quantity', models.IntegerField()),
                ('use', ckeditor.fields.RichTextField(max_length=255)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinicapp.medicine')),
                ('receipt_medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinicapp.receipt_medicine')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='receipt_medicine',
            name='medicines',
            field=models.ManyToManyField(blank=True, related_name='receipt_madicine', through='clinicapp.receipt_medicine_detail', to='clinicapp.medicine'),
        ),
        migrations.CreateModel(
            name='category_medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('update_date', models.DateField(auto_now_add=True)),
                ('name', models.CharField(max_length=255)),
                ('medicine', models.ManyToManyField(blank=True, related_name='category_medicine', to='clinicapp.medicine')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
