# Generated by Django 4.0.4 on 2022-05-20 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicapp', '0002_alter_bill_bill_receipt_medicine'),
    ]

    operations = [
        migrations.AddField(
            model_name='examination_schedule',
            name='authentication',
            field=models.BooleanField(default=False),
        ),
    ]
