# Generated by Django 4.0.4 on 2022-05-20 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicapp', '0003_examination_schedule_authentication'),
    ]

    operations = [
        migrations.CreateModel(
            name='regulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('update_date', models.DateField(auto_now_add=True)),
                ('maximum', models.IntegerField(default=100)),
                ('minimum', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
